package cli

import (
	"bytes"
	"encoding/json"
	"strings"
	"testing"

	"github.com/Overland-East-Bay/trip-planner-cli/internal/platform/exitcode"
)

func TestTripUpdate_Flags_ArtifactIDs_DedupPreserveFirst(t *testing.T) {
	stdout := &bytes.Buffer{}
	stderr := &bytes.Buffer{}
	store := &memStore{path: "/x", doc: baseDoc(t)}
	api := &fakePlannerAPI{}

	cmd := NewRootCmd(RootDeps{ConfigStore: store, PlannerAPI: api, Stdout: stdout, Stderr: stderr})
	cmd.SetArgs([]string{"trip", "update", "t1", "--artifact-id", "a", "--artifact-id", "b", "--artifact-id", "a", "--idempotency-key", "k1"})
	if err := cmd.Execute(); err != nil {
		t.Fatalf("execute: %v", err)
	}
	if api.updateCalls != 1 {
		t.Fatalf("expected 1 api call, got %d", api.updateCalls)
	}
	if api.lastUpdateReq.ArtifactIds == nil {
		t.Fatalf("expected artifactIds set")
	}
	got := *api.lastUpdateReq.ArtifactIds
	if len(got) != 2 || got[0] != "a" || got[1] != "b" {
		t.Fatalf("artifactIds: %#v", got)
	}
}

func TestTripUpdate_Flags_ClearArtifacts_MutuallyExclusiveWithArtifactID(t *testing.T) {
	stdout := &bytes.Buffer{}
	stderr := &bytes.Buffer{}
	store := &memStore{path: "/x", doc: baseDoc(t)}
	api := &fakePlannerAPI{}

	cmd := NewRootCmd(RootDeps{ConfigStore: store, PlannerAPI: api, Stdout: stdout, Stderr: stderr})
	cmd.SetArgs([]string{"trip", "update", "t1", "--clear-artifacts", "--artifact-id", "a"})
	err := cmd.Execute()
	if err == nil {
		t.Fatalf("expected error")
	}
	if exitcode.Code(err) != exitcode.Usage {
		t.Fatalf("expected exit 2, got %d (%v)", exitcode.Code(err), err)
	}
	if api.updateCalls != 0 {
		t.Fatalf("expected no api calls, got %d", api.updateCalls)
	}
}

func TestTripUpdate_Flags_MeetingLatLngMustBePair(t *testing.T) {
	stdout := &bytes.Buffer{}
	stderr := &bytes.Buffer{}
	store := &memStore{path: "/x", doc: baseDoc(t)}
	api := &fakePlannerAPI{}

	cmd := NewRootCmd(RootDeps{ConfigStore: store, PlannerAPI: api, Stdout: stdout, Stderr: stderr})
	cmd.SetArgs([]string{"trip", "update", "t1", "--meeting-lat", "1.23"})
	err := cmd.Execute()
	if err == nil {
		t.Fatalf("expected error")
	}
	if exitcode.Code(err) != exitcode.Usage {
		t.Fatalf("expected exit 2, got %d (%v)", exitcode.Code(err), err)
	}
	if api.updateCalls != 0 {
		t.Fatalf("expected no api calls, got %d", api.updateCalls)
	}
}

func TestTripUpdate_Flags_ClearMeetingLocation_MutuallyExclusive(t *testing.T) {
	stdout := &bytes.Buffer{}
	stderr := &bytes.Buffer{}
	store := &memStore{path: "/x", doc: baseDoc(t)}
	api := &fakePlannerAPI{}

	cmd := NewRootCmd(RootDeps{ConfigStore: store, PlannerAPI: api, Stdout: stdout, Stderr: stderr})
	cmd.SetArgs([]string{"trip", "update", "t1", "--clear-meeting-location", "--meeting-label", "x"})
	err := cmd.Execute()
	if err == nil {
		t.Fatalf("expected error")
	}
	if exitcode.Code(err) != exitcode.Usage {
		t.Fatalf("expected exit 2, got %d (%v)", exitcode.Code(err), err)
	}
	if api.updateCalls != 0 {
		t.Fatalf("expected no api calls, got %d", api.updateCalls)
	}
}

func TestTripUpdate_Flags_MultilineDescriptionRejected(t *testing.T) {
	stdout := &bytes.Buffer{}
	stderr := &bytes.Buffer{}
	store := &memStore{path: "/x", doc: baseDoc(t)}
	api := &fakePlannerAPI{}

	cmd := NewRootCmd(RootDeps{ConfigStore: store, PlannerAPI: api, Stdout: stdout, Stderr: stderr})
	cmd.SetArgs([]string{"trip", "update", "t1", "--description", "a\nb"})
	err := cmd.Execute()
	if err == nil {
		t.Fatalf("expected error")
	}
	if exitcode.Code(err) != exitcode.Usage {
		t.Fatalf("expected exit 2, got %d (%v)", exitcode.Code(err), err)
	}
	if api.updateCalls != 0 {
		t.Fatalf("expected no api calls, got %d", api.updateCalls)
	}
}

func TestTripUpdate_Flags_IdempotencyKeyAutoGenerated_JSONMeta(t *testing.T) {
	stdout := &bytes.Buffer{}
	stderr := &bytes.Buffer{}
	store := &memStore{path: "/x", doc: baseDoc(t)}
	api := &fakePlannerAPI{}

	cmd := NewRootCmd(RootDeps{ConfigStore: store, PlannerAPI: api, Stdout: stdout, Stderr: stderr})
	cmd.SetArgs([]string{"--output", "json", "trip", "update", "t1", "--name", "X"})
	if err := cmd.Execute(); err != nil {
		t.Fatalf("execute: %v", err)
	}
	if api.updateCalls != 1 {
		t.Fatalf("expected 1 api call, got %d", api.updateCalls)
	}

	var env map[string]any
	if err := json.Unmarshal(stdout.Bytes(), &env); err != nil {
		t.Fatalf("stdout not json: %v\n%s", err, stdout.String())
	}
	meta, _ := env["meta"].(map[string]any)
	if meta == nil {
		t.Fatalf("expected meta")
	}
	if meta["idempotencyKey"] == "" {
		t.Fatalf("expected meta.idempotencyKey")
	}
}

func TestTripUpdate_Flags_MeetingLocation_BuildsPayload(t *testing.T) {
	stdout := &bytes.Buffer{}
	stderr := &bytes.Buffer{}
	store := &memStore{path: "/x", doc: baseDoc(t)}
	api := &fakePlannerAPI{}

	cmd := NewRootCmd(RootDeps{ConfigStore: store, PlannerAPI: api, Stdout: stdout, Stderr: stderr})
	cmd.SetArgs([]string{
		"trip", "update", "t1",
		"--meeting-label", "Meet",
		"--meeting-address", "Addr",
		"--meeting-lat", "1.23",
		"--meeting-lng", "4.56",
		"--idempotency-key", "k1",
	})
	if err := cmd.Execute(); err != nil {
		t.Fatalf("execute: %v", err)
	}
	if api.lastUpdateReq.MeetingLocation == nil {
		t.Fatalf("expected meetingLocation set")
	}
	if api.lastUpdateReq.MeetingLocation.Label == nil || *api.lastUpdateReq.MeetingLocation.Label != "Meet" {
		t.Fatalf("label: %#v", api.lastUpdateReq.MeetingLocation.Label)
	}
	if api.lastUpdateReq.MeetingLocation.Address == nil || *api.lastUpdateReq.MeetingLocation.Address != "Addr" {
		t.Fatalf("address: %#v", api.lastUpdateReq.MeetingLocation.Address)
	}
	ll := api.lastUpdateReq.MeetingLocation.LatitudeLongitude
	if ll == nil || ll.Latitude == nil || ll.Longitude == nil {
		t.Fatalf("latlng: %#v", ll)
	}
	if *ll.Latitude != 1.23 || *ll.Longitude != 4.56 {
		t.Fatalf("latlng: %#v", ll)
	}
}

func TestTripUpdate_Flags_ClearMeetingLocation_SendsEmptyPatch(t *testing.T) {
	stdout := &bytes.Buffer{}
	stderr := &bytes.Buffer{}
	store := &memStore{path: "/x", doc: baseDoc(t)}
	api := &fakePlannerAPI{}

	cmd := NewRootCmd(RootDeps{ConfigStore: store, PlannerAPI: api, Stdout: stdout, Stderr: stderr})
	cmd.SetArgs([]string{"trip", "update", "t1", "--clear-meeting-location", "--idempotency-key", "k1"})
	if err := cmd.Execute(); err != nil {
		t.Fatalf("execute: %v", err)
	}
	if api.lastUpdateReq.MeetingLocation == nil {
		t.Fatalf("expected meetingLocation set")
	}
	if api.lastUpdateReq.MeetingLocation.Label != nil || api.lastUpdateReq.MeetingLocation.Address != nil || api.lastUpdateReq.MeetingLocation.LatitudeLongitude != nil {
		t.Fatalf("expected empty patch, got %#v", api.lastUpdateReq.MeetingLocation)
	}
}

func TestTripUpdate_Flags_AndFromFile_IsUsage_NoAPICall(t *testing.T) {
	stdout := &bytes.Buffer{}
	stderr := &bytes.Buffer{}
	store := &memStore{path: "/x", doc: baseDoc(t)}
	api := &fakePlannerAPI{}

	p := writeTempFile(t, "patch.yaml", "description: x\n")
	cmd := NewRootCmd(RootDeps{ConfigStore: store, PlannerAPI: api, Stdout: stdout, Stderr: stderr})
	cmd.SetArgs([]string{"trip", "update", "t1", "--from-file", p, "--name", "X"})
	err := cmd.Execute()
	if err == nil {
		t.Fatalf("expected error")
	}
	if exitcode.Code(err) != exitcode.Usage {
		t.Fatalf("expected exit 2, got %d (%v)", exitcode.Code(err), err)
	}
	if api.updateCalls != 0 {
		t.Fatalf("expected no api calls, got %d", api.updateCalls)
	}
}

func TestTripCreate_NameMultilineRejected(t *testing.T) {
	stdout := &bytes.Buffer{}
	stderr := &bytes.Buffer{}
	store := &memStore{path: "/x", doc: baseDoc(t)}
	api := &fakePlannerAPI{}

	cmd := NewRootCmd(RootDeps{ConfigStore: store, PlannerAPI: api, Stdout: stdout, Stderr: stderr})
	cmd.SetArgs([]string{"trip", "create", "--name", "a\nb"})
	err := cmd.Execute()
	if err == nil {
		t.Fatalf("expected error")
	}
	if exitcode.Code(err) != exitcode.Usage {
		t.Fatalf("expected exit 2, got %d (%v)", exitcode.Code(err), err)
	}
	if api.createCalls != 0 {
		t.Fatalf("expected no api calls, got %d", api.createCalls)
	}
}

func TestTripUpdate_Flags_IdempotencyKeyAutoGenerated_PrintsToStderr(t *testing.T) {
	stdout := &bytes.Buffer{}
	stderr := &bytes.Buffer{}
	store := &memStore{path: "/x", doc: baseDoc(t)}
	api := &fakePlannerAPI{}

	cmd := NewRootCmd(RootDeps{ConfigStore: store, PlannerAPI: api, Stdout: stdout, Stderr: stderr})
	cmd.SetArgs([]string{"trip", "update", "t1", "--name", "X"})
	if err := cmd.Execute(); err != nil {
		t.Fatalf("execute: %v", err)
	}
	if api.lastUpdateIdem == "" {
		t.Fatalf("expected generated idempotency key")
	}
	if !strings.Contains(stderr.String(), "Idempotency-Key: ") {
		t.Fatalf("stderr: %q", stderr.String())
	}
}
